feat: add MonoLisa font

diff --git a/.commitlint/hooks/commit-msg b/.commitlint/hooks/commit-msg
--- a/.commitlint/hooks/commit-msg
+++ b/.commitlint/hooks/commit-msg
@@ -2,11 +2,10 @@
 
 if ! type commitlint >/dev/null 2>/dev/null; then
 	echo ""
-    echo "commitlint could not be found"
-    echo "try again after installing commitlint or add commitlint to PATH"
+	echo "commitlint could not be found"
+	echo "try again after installing commitlint or add commitlint to PATH"
 	echo ""
-    exit 2;
+	exit 2
 fi
 
 commitlint lint --message $1
-
